version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6 # Invoke the Heroku orb
  node: circleci/node@2.0.2 # the node orb provides common node-related configuration

workflows:
matrix-tests:
    jobs:
      - node/test:
          version: 13.11.0
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git